# UI test fixture from the CCU Simplified Chinese language pack.
session-help-intro = 要开始使用，请描述任务或尝试以下命令：
session-help-init = 创建 AGENTS.md，为 Codex 提供项目说明
session-help-status = 显示当前会话配置
session-help-permissions = 选择 Codex 可以执行的操作
session-help-model = 选择模型和推理强度
session-help-review = 审查当前更改并查找问题
experimental-features-title = 实验性功能
experimental-features-subtitle = 开启或关闭实验性功能；更改会保存到 config.toml。
experimental-features-empty =   当前没有可用的实验性功能
experimental-features-hint-press = 按
experimental-features-hint-select = 切换选中状态，或按
experimental-features-hint-save = 保存并在下次对话中生效
ccu-welcome-back = 欢迎回来！
ccu-welcome-tips = 开始使用
ccu-welcome-commands = 常用命令
ccu-welcome-full-access = 完全访问权限
ccu-welcome-permissions = /permissions 查看访问权限
experimental-request-failed = 请求实验功能失败
experimental-page-limit = 实验功能分页超出请求数量限制
experimental-cursor-repeat = 实验功能分页游标重复
experimental-page-count = 实验功能列表超过 10 页
experimental-timeout = 获取实验功能超时
experimental-interrupted = 获取功能列表已中断
experimental-save-timeout = 保存实验功能超时，写入可能仍会完成。请重新打开 /experimental 检查。
experimental-save-failed = 保存实验功能失败。重试前请重新打开 /experimental 检查配置值。
experimental-readback-interrupted = 功能已保存，但读取结果时中断
experimental-overridden = 更改已保存，但配置值与所选项不同，可能被更高优先级的设置覆盖。
experimental-subagents = 子智能体
experimental-memories = 记忆
experimental-save-pending = 实验功能仍在保存中，请完成后再试。
experimental-loading = 正在加载服务器实验功能…
experimental-configured-hint = 勾选表示已配置启用。部分实验功能仅对新任务生效，或需要重启 Codex 服务。
experimental-saving-hint = 正在保存… 关闭此弹窗不会取消写入。
experimental-retained-hint = 已保留所选项。保存可重试，取消可关闭。
experimental-read-only = { " " }（只读）
experimental-saving = 正在保存实验功能…
experimental-save-interrupted = 保存已中断。请重新打开 /experimental 检查配置值。
experimental-discovery-interrupted = 获取列表已中断
experimental-none = 服务器暂无可用实验功能。
experimental-unavailable = 服务器实验功能不可用。请重新打开 /experimental 重试；若请求一直没有响应，请重启 Codex 客户端。
experimental-toggle-hint = { " " }切换
experimental-save-hint = { " " }保存
experimental-close-hint = { " " }保存/关闭
experimental-wait-startup = 启动完成前无法使用实验功能。
experimental-feature-analytics-plan-history-name = 方案用量历史
experimental-feature-analytics-plan-history-description = 在 /analytics 中预览个人账户的 5 小时及每周用量历史。
experimental-feature-network-proxy-name = 网络代理
experimental-feature-network-proxy-description = 对已获网络访问权限的沙箱会话应用网络代理限制。
experimental-feature-prevent-idle-sleep-name = 运行时防止休眠
experimental-feature-prevent-idle-sleep-description = 在 Codex 运行会话期间保持电脑唤醒。
experimental-feature-unadvertised = 服务器未提供实验功能 `{ $name }`
experimental-readback-failed = 功能已保存，但无法刷新配置值：{ $error }
questions-page = { $current } / { $total }
keymap-menu-hint-back = 返回
warnings-title = 警告
warnings-empty = 暂无警告
warnings-page = 警告 · { $value } / { $value2 } · { $value3 }
warnings-count-one = { $count } 条警告
warnings-count-many = { $count } 条警告
warnings-view-hint = { " " }查看
warnings-hint-copy = 复制
warnings-hint-warning = 切换警告
warnings-hint-scroll = 滚动
warnings-source-startup = 启动
warnings-source-warning = 警告
warnings-source-deprecation = 弃用提示
